FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD app-container.jar /opt/app-container/
EXPOSE 8080
WORKDIR /opt/app-container/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "app-container.jar"]
